name: CI pipeline
run-name: ${{ github.actor }} lets do this

on:
    push:
        branches:
            - "develop"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Print a message
              run: echo "Hello, world!"

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'  # Ajuste a versão do Python conforme necessário

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: pytest

    delivery:
      runs-on: ubuntu-latest
      needs: build
      if: ${{ success() }}
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.ACCESSS_TOKEN }}

        - name: Set up Git
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"

        - name: Merge to main
          run: |
            git fetch
            git checkout main
            git merge --no-ff develop --no-edit
            git push origin main
