import type { Metadata } from "next";
import  { Josefin_Sans, Roboto_Flex } from "next/font/google";
import { UserProvider } from "./context/userContext";
import "./globals.css";

const joseSans = Josefin_Sans({
  weight: "variable",
  variable: "--font-jose-sans",
  subsets: ["latin"]
});

const robotoFlex = Roboto_Flex({
  weight: "variable",
  variable: "--font-robo-flex",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Insight Miner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${joseSans.variable} ${robotoFlex.variable} `}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
