import type { Metadata } from "next";
import  { Josefin_Sans, Roboto_Flex } from "next/font/google";
import { UserProvider } from "./context/userContext";
import "./globals.css";
import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer";

const joseSans = Josefin_Sans({
  weight: "variable",
  variable: "--font-jose-sans",
  subsets: ["latin"]
});

const robotoFlex = Roboto_Flex({
  weight: "variable",
  variable: "--font-robo-flex",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Insight Miner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${joseSans.variable} ${robotoFlex.variable} `}>
        <div className="page">
            <Header /> {/* Componente Header */}
            <main>{children}</main> {/* O conteúdo da página vai aqui */}
            <Footer /> {/* Componente Footer */}
          </div>
      </body>
    </html>
  );
}
